<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>NavisAutoClash.Core</RootNamespace>
    <AssemblyName>NavisAutoClash.Core</AssemblyName>
  </PropertyGroup>

</Project>
